# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dir_mul_sample_cpp <- function(x, folds, b, epsilon) {
    .Call('_countsplit_dir_mul_sample_cpp', PACKAGE = 'countsplit', x, folds, b, epsilon)
}

mapply_dir_mul_sample_cpp <- function(x, folds, overdisps, epsilons) {
    .Call('_countsplit_mapply_dir_mul_sample_cpp', PACKAGE = 'countsplit', x, folds, overdisps, epsilons)
}

