# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rmultinom_1 <- function(size, probs) {
    .Call('_countsplit_rmultinom_1', PACKAGE = 'countsplit', size, probs)
}

dir_mul_sample_cpp <- function(size, folds, b) {
    .Call('_countsplit_dir_mul_sample_cpp', PACKAGE = 'countsplit', size, folds, b)
}

beta_bin_sample_cpp <- function(x, eps, b) {
    .Call('_countsplit_beta_bin_sample_cpp', PACKAGE = 'countsplit', x, eps, b)
}

mapply_dir_mul_sample_cpp <- function(x, folds, overdisps) {
    .Call('_countsplit_mapply_dir_mul_sample_cpp', PACKAGE = 'countsplit', x, folds, overdisps)
}

mapply_dir_mul_slower <- function(x, epsilon, overdisps) {
    .Call('_countsplit_mapply_dir_mul_slower', PACKAGE = 'countsplit', x, epsilon, overdisps)
}

mapply_betabin_sample_cpp <- function(x, eps1, overdisps) {
    .Call('_countsplit_mapply_betabin_sample_cpp', PACKAGE = 'countsplit', x, eps1, overdisps)
}

